# Generated by Django 2.0.2 on 2018-03-10 11:54

from django.db import migrations, models
import tracks.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='audio_file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[tracks.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='track_name',
            field=models.CharField(max_length=250),
        ),
    ]
