# Generated by Django 2.0.2 on 2018-03-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20180310_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='track_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
